#!/bin/bash

if [ -z "${GENODE_DEV_DIR}" ]
then
	echo "GENODE_DEV_DIR environment variable not defined"
	return -1
fi

d=$(echo ${GENODE_DEV_DIR}/imx8)

source $(echo ${d}/arm_v8a-hw-iot_gate)

# vim: ft=bash
