#!/bin/bash

if [ -z "${GENODE_DEV_DIR}" ]
then
	echo "GENODE_DEV_DIR environment variable not defined"
	return -1
fi

d=$(echo ${GENODE_DEV_DIR}/linux)

source $(echo ${d}/x86_64-linux)


# vim: ft=bash
